use gold;
select * from INFORMATION_SCHEMA.TABLES;
select * from INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='dim_customers';
-- 1. What countries do our customers come from?
select distinct country from gold.dim_customers;


-- 2. What are the distinct product categories, subcategories, and product names?
select distinct category,subcategory,product_name 
from gold.dim_products
order by category,subcategory,product_name;


-- 3. What is the date range of our orders in months?
select min(order_date) as first_order_date,
max(order_date) as last_order_date,
timestampdiff(month,min(order_date),max(order_date)) as order_range_month
from gold.fact_sales;


-- 4. What are the oldest and youngest customers, and their ages?
select min(birthdate) as oldest_birthdate,
max(birthdate) as youngest_birthdate,
timestampdiff(year,min(birthdate),curdate()) as oldest_age,
timestampdiff(year,max(birthdate),curdate()) as youngest_age
from gold.dim_customers;


-- 5. What is the total sales revenue?
select sum(sales_amount) as total_sales 
from gold.fact_sales;


-- 6. What is the total quantity of products sold?
select sum(quantity) as total_quantity 
from gold.fact_sales;


-- 7. What is the average product price?
select avg(price) 
from gold.fact_sales;


-- 8. How many unique orders do we have?
select count(distinct order_number) as total_orders 
from gold.fact_sales;


-- 9. How many sales records do we have?
select count(order_number) as total_orders 
from gold.fact_sales;


-- 10. How many unique products do we have?
select count(distinct product_key) as total_products 
from gold.dim_products;


-- 11. How many product records are in the product dimension?
select count(product_key) as total_products 
from gold.dim_products;


-- 12. How many unique customers have made purchases?
select count(distinct customer_key) as total_customer 
from gold.fact_sales;


-- 13. How many customers are in the customer dimension?
select count(customer_key) as total_customer 
from gold.dim_customers;


-- 14. What are the key business metrics: total sales, quantity, average price, orders, products, and customers?
select 'Total sales' as measure_name, sum(sales_amount) from gold.fact_sales
union all
select 'Total quantity' as measure_name, sum(quantity) from gold.fact_sales
union all
select 'AVG Price' as measure_name, avg(price) from gold.fact_sales
union all
select 'Total Nr. orders' as measure_name, count(order_number) from gold.fact_sales
union all
select 'Total Nr. products' as measure_name, count(product_key) from gold.dim_products
union all
select 'Total Nr. customers' as measure_name, count(customer_key) from gold.dim_customers;


-- 15. How many customers are there in each country?
select country, count(customer_key) as total_customers 
from gold.dim_customers 
group by country
order by total_customers;


-- 16. How many customers are there by gender?
select gender, count(customer_key) as total_customers 
from gold.dim_customers 
group by gender
order by total_customers;


-- 17. How many products are there in each category?
select category, count(product_key) as total_products 
from gold.dim_products 
group by category
order by total_products;


-- 18. What is the average product cost for each category?
select category, avg(cost) as avg_costs
from gold.dim_products
group by category
order by avg_costs desc;


-- 19. What is the total revenue generated by each product category?
select p.category, sum(f.sales_amount) as Total_Revenue 
from gold.fact_sales f
left join gold.dim_products p
on f.product_key=p.product_key
group by p.category
order by Total_Revenue;


-- 20. How much total revenue has each customer generated?
select c.customer_key,
concat(c.first_name,' ',c.last_name) as name,
sum(f.sales_amount) as Total_Revenue 
from gold.fact_sales f
left join gold.dim_customers c
on f.customer_key=c.customer_key
group by c.customer_key,name
order by Total_Revenue desc;


-- 21. How many items were sold in each country?
select c.country,
sum(f.quantity) as Total_Item_sold 
from gold.fact_sales f
left join gold.dim_customers c
on f.customer_key=c.customer_key
group by c.country
order by Total_Item_sold desc;


-- 22. What are the top 5 products by total revenue?
select p.product_name,
sum(f.sales_amount) as Total_Revenue 
from gold.fact_sales f
left join gold.dim_products p
on f.product_key=p.product_key
group by p.product_name
order by Total_Revenue desc
limit 5;


-- 23. What are the top 5 products by revenue ranking?
select p.product_name,
sum(f.sales_amount) as Total_Revenue,
dense_rank() over (order by sum(f.sales_amount) desc) as Ranking
from gold.fact_sales f
left join gold.dim_products p
on f.product_key=p.product_key
group by p.product_name
limit 5;


-- 24. What are the 5 products with the lowest total revenue?
select p.product_name,
sum(f.sales_amount) as Total_Revenue 
from gold.fact_sales f
left join gold.dim_products p
on f.product_key=p.product_key
group by p.product_name
order by Total_Revenue
limit 5;


-- 25. What are the 5 lowest-ranked products by revenue?
select *
from
(
    select p.product_name,
    sum(f.sales_amount) as Total_Revenue,
    dense_rank() over (order by sum(f.sales_amount)) as Ranking
    from gold.fact_sales f
    left join gold.dim_products p
    on f.product_key=p.product_key
    group by p.product_name
)t
where Ranking <= 5;


-- 26. What are the top 5 subcategories by total revenue?
select p.subcategory,
sum(f.sales_amount) as Total_Revenue 
from gold.fact_sales f
left join gold.dim_products p
on f.product_key=p.product_key
group by p.subcategory
order by Total_Revenue desc
limit 5;


-- 27. What are the 5 subcategories with the lowest total revenue?
select p.subcategory,
sum(f.sales_amount) as Total_Revenue 
from gold.fact_sales f
left join gold.dim_products p
on f.product_key=p.product_key
group by p.subcategory
order by Total_Revenue
limit 5;


-- 28. Who are the top 10 customers by total revenue?
select *
FROM
(
    select c.customer_key,
    concat(c.first_name,' ', c.last_name) as name,
    sum(f.sales_amount) as Total_Revenue,
    dense_rank() over (
        order by sum(f.sales_amount) DESC
    ) AS RANKING
    from gold.fact_sales f
    left join gold.dim_customers c
    on f.customer_key=c.customer_key
    group by c.customer_key,name
) t
where RANKING <= 10;


-- 29. Which 3 customers have placed the fewest orders?
select *
FROM
(
    select c.customer_key,
    concat(c.first_name,' ', c.last_name) as name,
    count(distinct f.order_number) as Total_ORDER,
    dense_rank() over (
        order by count(distinct f.order_number)
    ) AS RANKING
    from gold.fact_sales f
    left join gold.dim_customers c
    on f.customer_key=c.customer_key
    group by c.customer_key,name
) t
where RANKING <= 3
ORDER BY RANKING;